app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    password_hash = db.Column(db.String(255))
    Pitches =db.relationship('Pitch',backref = 'user', lazy ='dynamic')

    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String)
    Pitches =db.relationship('Pitch', backref = 'category', lazy ='dynamic')

    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    message = db.Column(db.String)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    upVotes = db.Column(db.Integer, default = 0)
    downVotes = db.Column(db.Integer, default = 0)
    category_id = db.Column(db.Integer, db.ForeignKey( "categories.id" ))
    user_id = db.Column(db.Integer, db.ForeignKey( "users.id" ))

    def __repr__(self):
        return f'User {self.message}'

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        pitches = Pitch.query.filter_by(category_id = id).all()
        return pitches

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    message = TextAreaField('Movie review',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # from .requests import configure_request
    # configure_request(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

    mail.init_app(app)
    simple.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Category, User, Pitch
from .. import db
from flask_login import login_required, current_user
import datetime
import markdown2

@main.route('/')
def index():
    categories = Category.query.all()
    add_category = request.args.get('add_category')
    if add_category:
        if add_category in categories:
            message="Category already exist"
        else:
            category = Category(name = add_category)
            db.session.add(category)
            db.session.commit()
            message = "Category added!! Go ahead and pitch in the created category"
            categories = Category.query.all()
        add_category=""
        return render_template('index.html',categories = categories, message=message)

    return render_template('index.html',categories = categories)



@main.route('/pitch/<category_id>', methods = ["GET","POST"])
def pitch(category_id):
    category = Category.query.filter(Category.id == category_id).first()
    categoryName = category.name
    add_pitch= request.args.get('add_pitch')
    if add_pitch:
        user = User.query.filter(User.id == current_user.id).first()
        user_id=user.id
        pitch = Pitch(message = add_pitch, category_id=category_id, user_id = user_id )
        db.session.add(pitch)
        db.session.commit()
        message = "Added successfully"
        pitches = Pitch.query.filter(Pitch.category_id == category_id).all()
        return render_template('pitches.html', pitches = pitches, category= categoryName, message = message)
    pitches = Pitch.query.filter(Pitch.category_id == category_id).all()
    return render_template('pitches.html', pitches = pitches, category= categoryName)

@main.route('/pitch/upVote/<pitch_id>/<int:upvote>', methods = ["GET","POST"])
@login_required
def upVote(pitch_id,upvote):
    upvote = upvote+1
    pitch = Pitch.query.filter_by(id =pitch_id).update({"upVotes":upvote})
    db.session.commit()
    pitch = Pitch.query.filter_by(id =pitch_id).first()
    category_id = pitch.category_id
    category = Category.query.filter(Category.id == category_id).first()
    categoryName = category.name
    pitches = Pitch.query.filter(Pitch.category_id == category_id).all()
    return redirect(url_for('main.pitch',category_id=category_id))

@main.route('/pitch/downVote/<pitch_id>/<int:downvote>', methods = ["GET","POST"])
@login_required
def downVote(pitch_id,downvote):
    downvote = downvote+1
    pitch = Pitch.query.filter_by(id =pitch_id).update({"downVotes":downvote})
    db.session.commit()
    pitch = Pitch.query.filter_by(id =pitch_id).first()
    category_id = pitch.category_id
    category = Category.query.filter(Category.id == category_id).first()
    categoryName = category.name
    pitches = Pitch.query.filter(Pitch.category_id == category_id).all()
    return redirect(url_for('main.pitch',category_id=category_id))

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles%}
    {{ super()}}
    <link href="https://fonts.googleapis.com/css?family=Rancho|Aclonica" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block scripts %}
  <script src="{{url_for('static', filename='js/scripts.js')}}"></script>
  {{super()}}
{%endblock%}

app/templates/index.html
{%  extends 'base.html' %}

{% block content%}
  <div class="container-fluid mainpage">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8 welcome">
          <h2>ONE MINUTE PITCH</h2>
          <p>Welcome to one minute pitch</p>
          <p>Suppose in your life, you only have 60 seconds to impress someone. 1 minute can make or break you!!!</p>
          <p>How will you use that one minute to say something meaningful??</p>
          {% if current_user.is_authenticated %}
          <p>You can create your own category to pitch in :<button onclick="toggle_display('.add_category')" type="submit" name="add_category">ADD A CATEGORY</button></p>
          <div class="add_category">
            <form>
              <p><input type="text" name="add_category" placeholder="Enter Category Name" class="form-control">
              <input type="submit"  value="Submit" class="btn btn-default">
              </p>

             </form>
          </div>
          <p><strong>{{message}}</strong></p>
          {%endif%}
          <p>You can select one of the existing categories to pitch in:<button onclick="toggle_display('.select_category')" type="submit" name="add_category">SELECT A CATEGORY</button></p>
          <div class="select_category">
            <ul>
              {%for category in categories%}
                <li><a href="{{url_for('main.pitch', category_id = category.id) }}">{{category.name}}</a></li>
              {% endfor %}
            </ul>
          </div>
          <h2>Use your one minute wisely!! Best of luck!!</h2>
        </div>
        <div class="col-md-2">
        </div>
      </div>
  </div>
{%endblock%}

app/templates/navbar.html
<div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"> ONE MINUTE PITCH </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                      Categories
                      </a>
                      <div class="dropdown-menu" aria-labelledby="Preview">
                      {%for category in categories%}
                      <a class="dropdown-item" href="{{url_for('main.pitch', category_id = category.id) }}">{{category.name}}</a>
                      {% endfor %}
                      </div>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                   <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">LOGOUT</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">LOGIN</a></li>
                  {%endif%}
                </ul>
            </div>

        </div>
    </div>

app/templates/pitches.html
{% extends 'base.html' %}
{% block content%}
<div class="container-fluid mainpage">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8 pitch">
      <h1>{{category}}:</h1>
      {% if current_user.is_authenticated %}
      <form >
        <p class= pitchForm>
          <textarea name="add_pitch"  placeholder="Add a new pitch" rows="6" cols="40" class="form-control"></textarea>
          <input type="submit" value="Pitch" class="btn btn-success btn-lg pitchBtn">
        </p>
      </form>
      <p>{{message}}</p>
      {%endif%}

      {% for pitch in pitches%}
      <br>
      <div class="card">
         <div class="container card-container">
             <p class="pitchMsg">" <strong>{{pitch.message}}</strong> "</p>
             <p>Posted on: {{pitch.posted}}</p>
             <p>UpVotes: {{pitch.upVotes}}</p>
             <p>DownVotes: {{pitch.downVotes}}</p>
             <p><button type="submit" class="btn btn-default btn-sm">
                 <a href="{{url_for('main.upVote', pitch_id = pitch.id, upvote = pitch.upVotes) }}"><span class="glyphicon glyphicon-thumbs-up"></span></a>
               </button>
               <button type="submit" class="btn btn-default btn-sm">
                 <a href="{{url_for('main.downVote', pitch_id = pitch.id, downvote = pitch.downVotes) }}"><span class="glyphicon glyphicon-thumbs-down"></span></a>
               </button>
             </p>
             <form >
               <p>
                 <input type="text" name="comment" value="comment"placeholder="What do you think about this pitch??" class="form-control" id="comment">
                 <input type="submit" value="Comment" class="btn btn-success btn-sm">
               </p>
             </form>
        </div>
      </div>



      {% endfor%}
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    
  </div>
</div>
{% endblock %}